#include "wb_eiface.h"
#include "actor.h"
#include "bots.h"
#include "network.h"
#include "r_state.h"
#include "team.h"
#include "doomerrors.h"
#include "sv_rcon.h"
#include "botcommands.h"
#include "st_hud.h"

void	SERVERCONSOLE_ReListPlayers(void);

namespace wbot {

	player_t* add_bot(CWootBot* pBot, int ulPlayerNum, const char* color, const char* colorSet,
		const char* skin, const char* pszTeamName) {
		ULONG	ulIdx;
		char	szColorizedBuffer[256];

		// Link the bot to the player.
		player_t* m_pPlayer = &players[ulPlayerNum];
		m_pPlayer->pWootBot = pBot;
		m_pPlayer->bIsBot = true;

		// [AK] Later on, PLAYER_ShouldSpawnAsSpectator gets called, which in turn
		// calls GAMEMODE_PreventPlayersFromJoining and then DUEL_CountActiveDuelers.
		// Thus, The bot's spectating status should be initialized to true, or else
		// they could be prevented from joining.
		m_pPlayer->bSpectating = true;
		m_pPlayer->bDeadSpectator = false;

		// [AK] Bots have a local connection to the host, so set their country index to LAN.
		m_pPlayer->ulCountryIndex = COUNTRYINDEX_LAN;

		// Update the playeringame slot.
		playeringame[ulPlayerNum] = true;

		// Setup the player's userinfo based on the bot's botinfo.
		// [BB] First clear the userinfo.
		m_pPlayer->userinfo.Reset();
		FString botname = "BOT";
		V_ColorizeString(botname);
		m_pPlayer->userinfo.NameChanged(botname);

		m_pPlayer->userinfo.ColorChanged(color);

		// Store the name of the skin the client gave us, so others can view the skin
		// even if the server doesn't have the skin loaded.
		if (NETWORK_GetState() == NETSTATE_SERVER)
			SERVER_GetClient(ulPlayerNum)->skinName = skin;

		LONG lSkin = R_FindSkin(skin, 0);
		m_pPlayer->userinfo.SkinNumChanged(lSkin);

		// If the skin was hidden, reveal it!
		if (skins[lSkin].bRevealed == false)
		{
			strcpy(szColorizedBuffer, skins[lSkin].name);
			V_ColorizeString(szColorizedBuffer);

			Printf("Hidden skin \"%s" TEXTCOLOR_NORMAL "\" has now been revealed!\n", szColorizedBuffer);
			skins[lSkin].bRevealed = true;
		}

		// [AK] Check if the bot should use a random player class whenever they spawn.
		m_pPlayer->userinfo.PlayerClassNumChanged(-1);

		// [AK] Get all the color set indices this bot's class has.
		if (m_pPlayer->userinfo.GetPlayerClassNum() != -1)
		{
			FName playerclass = m_pPlayer->userinfo.GetPlayerClassType()->TypeName;
			TArray<int> colorsets;
			P_EnumPlayerColorSets(playerclass, &colorsets);

			// [AK] See if the given color set name matches one of the class's color sets.
			for (ulIdx = 0; ulIdx < colorsets.Size(); ulIdx++)
			{
				if (stricmp(colorSet, P_GetPlayerColorSet(playerclass, colorsets[ulIdx])->Name.GetChars()) == 0)
				{
					m_pPlayer->userinfo.ColorSetChanged(ulIdx);
					break;
				}
			}
		}

		//m_pPlayer->userinfo.RailColorChanged(g_BotInfo[m_ulBotInfoIdx].ulRailgunColor);
		//m_pPlayer->userinfo.GenderNumChanged(D_GenderToInt(g_BotInfo[m_ulBotInfoIdx].szGender));
		if (pszTeamName)
		{
			// If we're in teamgame mode, put the bot on a defined team.
			if (GAMEMODE_GetCurrentFlags() & GMF_PLAYERSONTEAMS)
			{
				ULONG ulTeam = TEAM_GetTeamNumberByName(pszTeamName);
				if (TEAM_CheckIfValid(ulTeam))
					PLAYER_SetTeam(m_pPlayer, ulTeam, true);
				else
					PLAYER_SetTeam(m_pPlayer, TEAM_ChooseBestTeamForPlayer(), true);
			}
		}
		else
		{
			// In certain modes, the bot NEEDS to be placed on a team, or else he will constantly
			// respawn.
			if (GAMEMODE_GetCurrentFlags() & GMF_PLAYERSONTEAMS)
				PLAYER_SetTeam(m_pPlayer, TEAM_ChooseBestTeamForPlayer(), true);
		}

		// For now, bots always switch weapons on pickup.
		m_pPlayer->userinfo.SwitchOnPickupChanged(2);
		*static_cast<FIntCVar*>(m_pPlayer->userinfo[NAME_StillBob]) = 0;
		*static_cast<FIntCVar*>(m_pPlayer->userinfo[NAME_MoveBob]) = static_cast<fixed_t>(65536.f * 0.25);

		// If we've added the bot to a single player game, enable "fake multiplayer" mode.
		if (NETWORK_GetState() == NETSTATE_SINGLE)
			NETWORK_SetState(NETSTATE_SINGLE_MULTIPLAYER);

		m_pPlayer->playerstate = PST_ENTER;
		m_pPlayer->fragcount = 0;
		m_pPlayer->killcount = 0;
		m_pPlayer->ulDeathCount = 0;
		m_pPlayer->ulTime = 0;
		PLAYER_ResetSpecialCounters(m_pPlayer);

		// Check and see if this bot should spawn as a spectator.
		m_pPlayer->bSpectating = PLAYER_ShouldSpawnAsSpectator(m_pPlayer);

		// [BB] If the bot is forced to spectate, make sure he is not on a team.
		if (m_pPlayer->bSpectating)
			PLAYER_SetTeam(m_pPlayer, teams.Size(), true);

		// [BB] If any of the spawn functions throw an exception, we
		// have to catch it here. Otherwise the constructor is not properly
		// finished and trying to delete the pointer generated by it leads
		// to a crash.
		try
		{
			// [BB] Spawn the bot at its appropriate start.
			GAMEMODE_SpawnPlayer(ulPlayerNum, true);
		}
		catch (CRecoverableError&/*error*/)
		{
			Printf("Unable to spawn bot %s.\n", players[ulPlayerNum].userinfo.GetName());
			m_pPlayer->bSpectating = true;
			return m_pPlayer;
		}

		if (NETWORK_GetState() != NETSTATE_SERVER)
			Printf("%s entered the game.\n", players[ulPlayerNum].userinfo.GetName());
		else
		{
			// Let the other players know that this bot has entered the game.
			SERVER_Printf("%s entered the game.\n", players[ulPlayerNum].userinfo.GetName());

			// Redo the scoreboard.
			SERVERCONSOLE_ReListPlayers();

			// [RC] Update clients using the RCON utility.
			SERVER_RCON_UpdateInfo(SVRCU_PLAYERDATA);

			// Now send out the player's userinfo out to other players.
			SERVERCOMMANDS_SetAllPlayerUserInfo(ulPlayerNum);

			// If this player is on a team, tell all the other clients that a team has
			// been selected for him.
			if (m_pPlayer->bOnTeam)
				SERVERCOMMANDS_SetPlayerTeam(ulPlayerNum);
		}

		BOTCMD_SetLastJoinedPlayer(m_pPlayer->userinfo.GetName());

		// Tell the bots that a new players has joined the game!
		{
			ULONG	ulIdx;

			for (ulIdx = 0; ulIdx < MAXPLAYERS; ulIdx++)
			{
				if (playeringame[ulIdx] == false)
					continue;

				// Don't tell the bot that joined that it joined the game.
				if (ulIdx == ulPlayerNum)
					continue;

				if (players[ulIdx].pSkullBot)
					players[ulIdx].pSkullBot->PostEvent(BOTEVENT_PLAYER_JOINEDGAME);
			}
		}

		// Refresh the HUD since a new player is now here (this affects the number of players in the game).
		HUD_ShouldRefreshBeforeRendering();

		return m_pPlayer;
	}

	float get_player_use_distance(APlayerPawn* plr) {
		return plr->UseRange / (float)FRACUNIT;
	}
};