name: CI

on: [push, pull_request]

jobs:
  build-linux-server:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install build dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install g++ make cmake libsdl1.2-dev mercurial zlib1g-dev libbz2-dev libjpeg-dev libfluidsynth-dev libgtk2.0-dev timidity nasm libgl1-mesa-dev libssl-dev tar libglew-dev wget libopus-dev

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }} -S ${{ github.workspace }}
        -DCMAKE_BUILD_TYPE=Release
        -DSERVERONLY=ON
        -DRELEASE_WITH_DEBUG_FILE=ON

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release -j $(nproc)

    - name: Create package
      shell: bash
      run: |
        mkdir package
        if [[ "${{ runner.os }}" == 'Linux' ]]; then
          cp ${{ steps.strings.outputs.build-output-dir }}/zandronum* package
          cp ${{ steps.strings.outputs.build-output-dir }}/*.pk3 package
          cp ${{ steps.strings.outputs.build-output-dir }}/*.so package || true
          cp ${FMOD_LIBRARY} package || true
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: package
        name: linux-server

  wbot-tests-linux:
    runs-on: ubuntu-24.04
    needs: [build-linux-server]

    steps:
    - uses: actions/checkout@v4

    - name: Install runtime dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install libsdl1.2debian

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: linux-server
        path: tests

    - name: Download test files
      run: |
          cd tests
          wget -q https://github.com/redox-os/freedoom/raw/refs/heads/master/freedoom2.wad
          wget -q https://w00tguy.ddns.net/files/doom/doom2_maps_v0.7z
          7z x doom2_maps_v0.7z
          chmod +x zandronum-server

    - name: Beat Doom II
      run: |
          cd tests
          ./zandronum-server -config test_doom2.ini -wbtest
